apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clear-sessions
  namespace: edu-practical-goldwasser
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 20
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 70
      template:
        spec:
          containers:
            - name: django-clear-sessions
              image: miazigoo/django_app:f9cb8d0
              ports:
                - containerPort: 80
              imagePullPolicy: IfNotPresent
              command:
                - python
                - manage.py
                - clearsessions
              envFrom:
                - configMapRef:
                    name: django-app-config
                - secretRef:
                    name: django-secret-config
          restartPolicy: OnFailure