apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
  namespace: dev
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 30
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: django-migrate
          image: django_app:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Never
          command: [ "python", "manage.py", "migrate", "--no-input" ]
          envFrom:
            - configMapRef:
                name: django-app-config
      restartPolicy: Never